-- Oct-30-ready: opt in early, then grant explicitly next to every RLS policy.
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role, public;

create table if not exists public.todos (
  id bigserial primary key,
  user_id uuid not null default auth.uid(),
  task text not null,
  done boolean default false
);
alter table public.todos enable row level security;
create policy "own todos" on public.todos for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
grant select, insert, update, delete on table public.todos to authenticated;
grant select, insert, update, delete on table public.todos to service_role;
grant usage, select on sequence public.todos_id_seq to authenticated, service_role;

create table public.audit_log (id bigint generated by default as identity primary key, msg text);
alter table public.audit_log enable row level security;
grant all on public.audit_log to service_role; -- server-only on purpose

create function public.todo_count() returns bigint
  language sql stable security invoker set search_path = ''
  as $$ select count(*) from public.todos $$;
revoke execute on function public.todo_count() from public;
grant execute on function public.todo_count() to authenticated;

create or replace view public.my_todos with (security_invoker = on) as
  select id, task from public.todos where done = false;
grant select on public.my_todos to authenticated;

-- internal helper table, never meant for the Data API:
-- supabase-security: ignore
create table public.internal_jobs (id int primary key, payload jsonb);

-- private schema is not exposed, so nothing to report here
create schema if not exists private;
create table private.billing (id int primary key, amount int);
grant all on private.billing to anon;
