/* Block comment that mentions create table public.ghost_in_comment (id int);
   /* nested: grant all on all tables in schema public to anon; */
   still a comment */
-- create table public.ghost_line_comment (id int);

CREATE TABLE IF NOT EXISTS "public"."Customers" (
  "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" TEXT DEFAULT 'create table public.ghost_in_default (x int); grant all on all tables in schema public to anon'
);
CREATE TABLE IF NOT EXISTS "public"."Customers" ("Id" bigint);   -- no-op re-run
ALTER TABLE ONLY "public"."Customers" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Staff read" ON "public"."Customers" AS PERMISSIVE FOR SELECT TO "authenticated" USING (true);
GRANT SELECT ON TABLE "public"."Customers" TO "authenticated";
GRANT ALL ON TABLE "public"."Customers" TO "service_role";

-- implicit public schema
create table invoices (id uuid primary key, note text default E'it''s; \'quoted\'; create table x();');
alter table invoices enable row level security;
grant select on invoices to authenticated;
grant all on invoices to service_role;

-- function body mentions create table / grant to anon, must not count
create or replace function public.make_report() returns void
language plpgsql security invoker set search_path = public as $body$
begin
  execute 'create table public.ghost_in_body (id int)';
  create table if not exists public.ghost_in_body2 (id int);
  grant select on public.invoices to anon;
end;
$body$;
grant execute on function public.make_report() to service_role;

-- SQL-standard body with semicolons inside
create function public.two() returns int language sql
begin atomic
  select case when true then 2 else 1 end;
end;
grant execute on function public.two() to authenticated;

-- DO blocks are not replayed
do $$ begin create table public.ghost_in_do (id int); end $$;

-- rename + drop
create table public.tmp_old (id int);
alter table public.tmp_old rename to tmp_new;
grant select on public.tmp_new to service_role;
create table public.gone (id int);
drop table if exists public.gone cascade;

-- search_path switch: unqualified names land in api
set search_path to api, public;
create table widgets (id int primary key);
grant select on widgets to authenticated;
alter table widgets enable row level security;
reset search_path;
